### ISSUE TITLE
Vertification failure?

### ISSUE THREAD

**Issue by ghost** [analogic/lemanager#4]
I have installed LEManager and have it running fine apart from it is trying to verify the domain with something called "./well-known" which is responding with the error message below.

[2016-09-13 10:26:18] INFO: Account already registered. Continuing.
[2016-09-13 10:26:18] INFO: Starting certificate generation process for domains
[2016-09-13 10:26:18] INFO: Requesting challenge for ***_.com
[2016-09-13 10:26:18] INFO: Sending signed request to /acme/new-authz
[2016-09-13 10:26:19] INFO: Got challenge token for ***_.com
[2016-09-13 10:26:19] INFO: Token for ***_.com saved at /opt/lemanager/web//.well-known/acme-challenge/Z4Q4v-g-Zz5v3AtC--MGLwBZtPSmgp1M4qG5wTrClZ0 and should be available at http://**_*.com/.well-known/acme-challenge/Z4Q4v-g-Zz5v3AtC--MGLwBZtPSmgp1M4qG5wTrClZ0
[2016-09-13 10:26:20] ERROR: Please check $1 - token not available
[2016-09-13 10:26:20] DEBUG: #0 /opt/lemanager/src/Command/IssueNewCommand.php(39): Analogic\ACME\Lescript->signDomains(Array, true)
[2016-09-13 10:26:20] DEBUG: #1 /opt/lemanager/vendor/symfony/console/Command/Command.php(256): App\Command\IssueNewCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[2016-09-13 10:26:20] DEBUG: #2 /opt/lemanager/vendor/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[2016-09-13 10:26:20] DEBUG: #3 /opt/lemanager/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Command\IssueNewCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[2016-09-13 10:26:20] DEBUG: #4 /opt/lemanager/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
[2016-09-13 10:26:20] DEBUG: #5 /opt/lemanager/bin/cli.php(12): Symfony\Component\Console\Application->run()
[2016-09-13 10:26:20] DEBUG: #6 {main}

Is there a way to fix this error and what can I do to resolve this?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/6277379/18470834/7672c0e4-79a6-11e6-9f1e-044fc758c101.png)
